[global]
disableWidgetStateDuplicationWarning = false
showWarningOnDirectExecution = true

[theme]
base="dark"
primaryColor = "#1E90FF"
backgroundColor = "#F0F0F0"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"